name: Brewski
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  主页: /
  归档: /archives/
  说说: /talk/
  留言: /comment/
  关于: /about/
  订阅: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Valine
valine: true
appID: 6PQcTkHfheSIKOymTCUbiDsc-MdYXbMMI
appKey: wfyWbG3H3Yxfwq2KLiphW0NI
serverURLs: https://waline-mu.vercel.app
placeHolder: ''
visitor: true

# Copyright Infomation
copyright:
  since: 2018
  name: amtoaer
  url: https://blog.allwens.work
