name: Brewski
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  主页: /
  归档: /archives/
  说说: /talk/
  友链: /friends/
  留言: /comment/
  关于: /about/

favicon: /favicon.svg
logo: /logo.svg

# Valine
valine:
  serverURLs: https://waline-mu.vercel.app
  placeHolder: ""
  visitor: true

artitalk:
  appID: "BB47PurCV8enSBEjrXL7RSmz-MdYXbMMI"
  appKey: "MwwGckMof2je5drCC3AnFtjw"

# Copyright Infomation
copyright:
  since: 2018
  name: amtoaer
  url: https://blog.allwens.work
