name: Brewski
url: https://github.com/tiaanduplessis/hexo-theme-brewski

menu:
  Home: /
  About: /about
  Archives: /archives
  Impressum: amtoaer
  GitHub: https://github.com/amtoaer
  RSS: /atom.xml

favicon: /favicon.svg
logo: /logo.svg

# Valine
valine: true
appID: 6PQcTkHfheSIKOymTCUbiDsc-MdYXbMMI
appKey: wfyWbG3H3Yxfwq2KLiphW0NI
placeHolder: ''
visitor: true

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since: 2018
  name: amtoaer
  url: https://blog.allwens.work
